Repository wedinc/hydrangea, pull requests merged in 2023-10, with the labels that each got.

#13 fetch Hackernews
  pages/caramel/index.tsx
Labels: 🔍 Ready for Review, ✅ Approved

#18 Add new component to display API response information
  components/Card.tsx
  pages/caramel/index.tsx
Labels: ✅ Approved

#21 fix caramel page design
  components/ListItem.tsx
  package-lock.json
  package.json
  pages/caramel/index.tsx
Labels: 🔍 Ready for Review
